name: Update RSS Feed (Refreshed)

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Hello from RSS workflow
        run: echo "✅ RSS workflow loads correctly"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Debug current directory
        run: |
          echo "PWD: $(pwd)"
          echo "Listing:"
          ls -la

      - name: Run RSS generator
        run: |
          cd /home/runner/work/clean-rss-feed/clean-rss-feed/
          python generate_rss.py

      - name: Add timestamp to force update
        run: echo "<!-- Updated: $(date -u) -->" >> rss.xml

      - name: Commit and push updated RSS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add rss.xml

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated RSS update"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          fi
