name: Update RSS Feed (Test Mode)

on:
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Hello from RSS update
        run: echo "🧪 RSS workflow loads correctly"
