name: Update RSS Feed (Test Mode)

on:
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Hello from RSS workflow
        run: echo "✅ RSS workflow loads correctly"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser
     
      - name: Set working directory
        run: cd $GITHUB_WORKSPACE

      - name: Run RSS generator
        run: python $GITHUB_WORKSPACE/generate_rss.py
