name: Update RSS Feed

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run RSS generator
        run: |
          python generate_rss.py
          echo "<!-- Updated: $(date -u) -->" >> rss.xml

      - name: Commit and push updated RSS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add rss.xml
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Automated RSS update"
          git push
